class PlannersData {
  static final getData = [
    {
      'name': '4 Seasons Events',
      'image': 'assets/planners/pic1.jpg',
      'location': 'Mumbai',
      'events': 'Wedding, Bachlorette, Parties',
      'number': '9956751925',
    },
    {
      'name': 'Bait Al Dana',
      'image': 'assets/planners/pic2.jpg',
      'location': 'Mumbai',
      'events': 'Exhibitions, Grand Events, Parties, Wedding',
      'number': '9678751925',
    },
    {
      'name': '4 Seasons Events',
      'image': 'assets/planners/pic3.jpg',
      'location': 'Mumbai',
      'events': 'Wedding, Bachlorette, Parties',
      'number': '7956751925',
    },
    {
      'name': 'Liliss Events',
      'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRYDrcRZnkKUKxjqRMrs6TnvJg7wFee5AVVQ&usqp=CAU',
      'location': 'Thane',
      'events': 'Wedding, Baby Shower, Parties',
      'number': '8954451934',
    },
    {
      'name': 'Rose Palace Weddings',
      'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqvpHc2AYm9yJZKXr8OBD_LXK7bxx0SMCpIQ&usqp=CAU',
      'location': 'Pune',
      'events': 'Wedding',
      'number': '9023451937',
    },
    {
      'name': 'The Event Houzz',
      'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLZVK4rr0txG7TS9iGBhB61IcMH0QN5pWH6Q&usqp=CAU',
      'location': 'Powai',
      'events': 'Birthdays & Anniversaries, Baby showers',
      'number': '7022451932',
    },
    {
      'name': 'Fabulous Day',
      'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVwVtDMwDRPm96gFvXMT7dUkqkP_JGKQB8vA&usqp=CAU',
      'location': 'Andheri',
      'events': 'Bachlorette, Birthdays & Anniversaries, Weddings',
      'number': '8137451990',
    },
    {
      'name': 'Snow White',
      'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBAdbWIHDWfG_3qRlvl4dW5uLXVDT2US6eiA&usqp=CAU',
      'location': 'Thane',
      'events': 'Weddings, Bachlorette, Baby showers',
      'number': '7137451990',
    },
    {
      'name': 'Saz Events',
      'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR13lEiVcH52PBbztCX_abI1ClaG7uv5fFLPw&usqp=CAU',
      'location': 'Thane',
      'events': 'Grand Events, Bachlorette, Birthdays & Anniversaries',
      'number': '7256451988',
    },
    {
      'name': 'Slendid Surprise',
      'image': 'https://www.adventurecity.com/wp-content/uploads/2021/07/party-tree-house-1-1280x720.jpg',
      'location': 'Mumbai',
      'events': 'Weddings, Bachlorette, Birthdays & Anniversaries',
      'number': '9234651978',
    },
    {
      'name': 'The Moments',
      'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUVfOueJkbhONhWC1z2rxhUls1SZoS3ubKIQ&usqp=CAU',
      'location': 'Powai',
      'events': 'Birthdays & Anniversaries, Baby showers',
      'number': '9922451935',
    },
  ];
}
